/**
 * LatentSpaceMap
 * ──────────────────────────────────────────────────────────────────────────────
 * Interactive 2D projection of the CVAE latent space.
 *
 * Requires public/latent_map.json generated by:
 *   python scripts/generate_map.py
 *
 * Interactions
 * ─────────────
 * • Hover   → patch name tooltip
 * • Click on a point  → decode its z_vector (or use stored params) → send NRPNs
 * • Click in empty space → KNN (k=5) IDW interpolation of surrounding
 *   z_vectors or param-vectors → decode → send NRPNs
 * • Crosshair  → shows the position of the current patch in the map
 *   (nearest neighbour by Euclidean distance on the 37-dim param vector)
 * • Category filter buttons → highlight / isolate a sound category
 */

import {
  useState, useEffect, useRef, useMemo, useCallback,
} from 'react';
import styled from 'styled-components';
import { useCurrentPatch } from '../stores/patchStore';
import { useMidiStore } from '../midi/usePreenFM3Midi';
import { patchToNRPNMessages } from '../midi/patchSerializer';
import { sendNRPN, clearNRPNQueue, drainNRPNQueue } from '../midi/midiService';
import {
  variator,
  patchToParamVector,
  paramVectorToPatch,
  enforceValidity,
  Z_OSC_DIM,
  Z_ENV_DIM,
  Z_MATRIX_DIM,
} from '../ml/patchVariator';
import type { Patch } from '../types/patch';

// ── Constants ──────────────────────────────────────────────────────────────────

const CATEGORY_COLORS: Record<string, string> = {
  BASS:  '#3b82f6',
  LEAD:  '#ef4444',
  PAD:   '#8b5cf6',
  PERC:  '#f59e0b',
  PLUCK: '#10b981',
  SFX:   '#6b7280',
};

const KNN_K      = 5;    // neighbours for IDW interpolation
const HIT_PX     = 14;   // pixel radius to detect a direct point click
const PARAM_DIM  = 37;   // FM parameter vector length used for crosshair distance
const CANVAS_PAD = 24;   // padding between canvas edge and the point cloud

// ── Types ──────────────────────────────────────────────────────────────────────

interface MapPoint {
  name:     string;
  x:        number;       // normalised [0, 1]
  y:        number;
  z_vector: number[];     // 12-dim; empty when has_z_vectors=false
  params:   number[];     // 85-dim  — always present (37-dim in legacy JSON)
  category: string;
  // Structured-head coordinates (present when mapData.structured === true)
  x_timbre?:    number; y_timbre?:    number;
  x_dynamics?:  number; y_dynamics?:  number;
  x_modulation?: number; y_modulation?: number;
}

interface MapData {
  has_z_vectors: boolean;
  latent_dim:    number;
  method:        string;
  points:        MapPoint[];
  // Structured latent space (3-head CVAE)
  structured?:   boolean;
  z_osc_dim?:    number;
  z_env_dim?:    number;
  z_matrix_dim?: number;
}

// ── Styled components ──────────────────────────────────────────────────────────

const Container = styled.div`
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 16px;
  background: ${({ theme }) => theme.colors.panel};
  border: 1px solid ${({ theme }) => theme.colors.border};
  border-radius: 10px;
  max-width: 900px;
  margin: 0 auto;
`;

const Header = styled.div`
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  flex-wrap: wrap;
  gap: 8px;
`;

const Title = styled.h3`
  margin: 0;
  font-size: 1rem;
  font-weight: 700;
  color: ${({ theme }) => theme.colors.text};
  letter-spacing: 0.03em;
`;

const StatusRow = styled.div`
  display: flex;
  gap: 6px;
  flex-wrap: wrap;
`;

const StatusTag = styled.span`
  font-size: 0.7rem;
  font-family: monospace;
  color: ${({ theme }) => theme.colors.textMuted};
  border: 1px solid ${({ theme }) => theme.colors.border};
  border-radius: 4px;
  padding: 2px 8px;
`;

const FilterRow = styled.div`
  display: flex;
  align-items: center;
  gap: 5px;
  flex-wrap: wrap;
`;

const FilterLabel = styled.span`
  font-size: 0.72rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.07em;
  color: ${({ theme }) => theme.colors.textMuted};
`;

const FilterBtn = styled.button<{ $active: boolean; $color?: string }>`
  padding: 3px 10px;
  border-radius: 4px;
  border: 1px solid ${({ $color, $active, theme }) =>
    $active && $color ? $color : theme.colors.border};
  background: ${({ $color, $active }) => ($active && $color) ? `${$color}2a` : 'transparent'};
  color: ${({ $color, $active, theme }) =>
    $active && $color ? $color : theme.colors.textMuted};
  font-size: 0.69rem;
  font-weight: 600;
  cursor: pointer;
  transition: opacity 0.15s;
  &:hover { opacity: 0.8; }
`;

const CanvasWrap = styled.div`
  position: relative;
  width: 100%;
  border-radius: 6px;
  overflow: hidden;
  background: #0d1117;
`;

const StyledCanvas = styled.canvas`
  display: block;
  width: 100%;
  image-rendering: crisp-edges;
`;

const Overlay = styled.div`
  position: absolute;
  inset: 0;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  background: rgba(13, 17, 23, 0.88);
  color: #6b7280;
  font-size: 0.82rem;
  font-family: monospace;
  text-align: center;
  padding: 16px;
  gap: 8px;

  code {
    background: #1e2840;
    padding: 4px 10px;
    border-radius: 4px;
    font-size: 0.76rem;
    color: #10b981;
  }
`;

const Tooltip = styled.div`
  position: absolute;
  pointer-events: none;
  background: rgba(13, 17, 23, 0.92);
  border: 1px solid #30384a;
  border-radius: 6px;
  padding: 5px 9px;
  white-space: nowrap;
  z-index: 10;
`;

const TooltipName = styled.div`
  font-size: 0.75rem;
  font-weight: 700;
  font-family: monospace;
  color: #e5e7eb;
`;

const TooltipCat = styled.div<{ $color: string }>`
  font-size: 0.64rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: ${({ $color }) => $color};
`;

const Legend = styled.div`
  display: flex;
  gap: 14px;
  flex-wrap: wrap;
  align-items: center;
`;

const LegendItem = styled.div`
  display: flex;
  align-items: center;
  gap: 5px;
  font-size: 0.67rem;
  color: ${({ theme }) => theme.colors.textMuted};
`;

const LegendDot = styled.div<{ $color: string }>`
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: ${({ $color }) => $color};
`;

const LegendCrosshair = styled.div`
  width: 10px;
  height: 10px;
  border: 1.5px solid rgba(255, 255, 255, 0.6);
  border-radius: 50%;
`;

const HintRow = styled.div`
  font-size: 0.67rem;
  font-style: italic;
  color: ${({ theme }) => theme.colors.textMuted};
  opacity: 0.65;
  text-align: center;
`;

const StructuredSection = styled.div`
  border-top: 1px solid ${({ theme }) => theme.colors.border};
  padding-top: 12px;
`;

const StructuredTitle = styled.div`
  font-size: 0.72rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  color: ${({ theme }) => theme.colors.textMuted};
  margin-bottom: 8px;
`;

const MapsGrid = styled.div`
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 10px;
`;

const MiniMapWrap = styled.div`
  display: flex;
  flex-direction: column;
  gap: 4px;
`;

const MiniMapLabel = styled.div`
  font-size: 0.67rem;
  font-weight: 700;
  font-family: monospace;
  color: ${({ theme }) => theme.colors.textMuted};
  text-align: center;
`;

const MiniCanvas = styled.canvas`
  display: block;
  width: 100%;
  border-radius: 4px;
  background: #0d1117;
  image-rendering: crisp-edges;
`;

// ── Component ──────────────────────────────────────────────────────────────────

export function LatentSpaceMap() {
  // ── Data state ────────────────────────────────────────────────────────────
  const [mapData,   setMapData]   = useState<MapData | null>(null);
  const [mapStatus, setMapStatus] = useState<'loading' | 'error' | 'ready'>('loading');
  const [modelReady, setModelReady] = useState(variator.weightsLoaded);

  // ── Interaction state ─────────────────────────────────────────────────────
  const [hoveredIdx,   setHoveredIdx]   = useState<number | null>(null);
  const [tooltipStyle, setTooltipStyle] = useState<React.CSSProperties>({});
  const [activeNorm,   setActiveNorm]   = useState<{x:number;y:number} | null>(null);
  const [sending,      setSending]      = useState(false);
  const [filterCat,    setFilterCat]    = useState<string | null>(null);

  // ── Structured map hover / active state ──────────────────────────────────
  const [hoverTimbre,   setHoverTimbre]   = useState<number | null>(null);
  const [hoverDyn,      setHoverDyn]      = useState<number | null>(null);
  const [hoverMod,      setHoverMod]      = useState<number | null>(null);
  const [activeTimbre,  setActiveTimbre]  = useState<{x:number;y:number} | null>(null);
  const [activeDyn,     setActiveDyn]     = useState<{x:number;y:number} | null>(null);
  const [activeMod,     setActiveMod]     = useState<{x:number;y:number} | null>(null);

  // ── Stores ────────────────────────────────────────────────────────────────
  const currentPatch = useCurrentPatch();
  const midiOutput   = useMidiStore(s => s.selectedOutput);
  const midiChannel  = useMidiStore(s => s.channel);

  // ── Canvas refs ───────────────────────────────────────────────────────────
  const canvasRef   = useRef<HTMLCanvasElement>(null);
  const wrapRef     = useRef<HTMLDivElement>(null);
  const [canvasW,   setCanvasW]   = useState(700);
  const [canvasH,   setCanvasH]   = useState(500);

  // Structured mini-map refs and sizes
  const timbreCanvasRef   = useRef<HTMLCanvasElement>(null);
  const dynCanvasRef      = useRef<HTMLCanvasElement>(null);
  const modCanvasRef      = useRef<HTMLCanvasElement>(null);
  const mapsGridRef       = useRef<HTMLDivElement>(null);
  const [miniW, setMiniW] = useState(280);
  const [miniH, setMiniH] = useState(200);

  // ── Coordinate transforms (normalised ↔ canvas pixels) ────────────────────
  const toCanvas = useCallback((nx: number, ny: number) => ({
    x: CANVAS_PAD + nx * (canvasW - 2 * CANVAS_PAD),
    y: CANVAS_PAD + ny * (canvasH - 2 * CANVAS_PAD),
  }), [canvasW, canvasH]);

  const fromCanvas = useCallback((cx: number, cy: number) => ({
    x: (cx - CANVAS_PAD) / Math.max(canvasW - 2 * CANVAS_PAD, 1),
    y: (cy - CANVAS_PAD) / Math.max(canvasH - 2 * CANVAS_PAD, 1),
  }), [canvasW, canvasH]);

  // ── Crosshair: nearest precomputed point to the current patch ─────────────
  const crosshairNorm = useMemo((): { x: number; y: number } | null => {
    if (!currentPatch || !mapData?.points.length) return null;
    const src = patchToParamVector(currentPatch);
    let bestIdx = 0;
    let bestDist = Infinity;
    for (let i = 0; i < mapData.points.length; i++) {
      const p = mapData.points[i];
      if (!p.params.length) continue;
      let sq = 0;
      const len = Math.min(src.length, p.params.length, PARAM_DIM);
      for (let d = 0; d < len; d++) sq += (src[d] - p.params[d]) ** 2;
      if (sq < bestDist) { bestDist = sq; bestIdx = i; }
    }
    return { x: mapData.points[bestIdx].x, y: mapData.points[bestIdx].y };
  }, [currentPatch, mapData]);

  // ── Load map JSON ─────────────────────────────────────────────────────────
  useEffect(() => {
    fetch('/latent_map.json')
      .then(r => r.ok ? r.json() : Promise.reject(`HTTP ${r.status}`))
      .then((data: MapData) => { setMapData(data); setMapStatus('ready'); })
      .catch(err => {
        console.warn('[LatentSpaceMap] /latent_map.json not available:', err);
        setMapStatus('error');
      });
  }, []);

  // ── Load CVAE weights (shared with PatchVariatorEditor) ───────────────────
  useEffect(() => {
    if (variator.weightsLoaded) { setModelReady(true); return; }
    variator.loadWeights('/models/encoder/model.json', '/models/decoder/model.json')
      .then(() => setModelReady(true))
      .catch(() => setModelReady(false));
  }, []);

  // ── Responsive canvas size via ResizeObserver ─────────────────────────────
  useEffect(() => {
    const el = wrapRef.current;
    if (!el) return;
    const ro = new ResizeObserver(entries => {
      const w = Math.floor(entries[0].contentRect.width);
      const h = Math.floor(Math.max(w * 0.65, 320));
      setCanvasW(w);
      setCanvasH(h);
    });
    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  // ── Mini-map resize observer (structured section) ─────────────────────────
  useEffect(() => {
    const el = mapsGridRef.current;
    if (!el) return;
    const ro = new ResizeObserver(entries => {
      const totalW = Math.floor(entries[0].contentRect.width);
      const cellW  = Math.max(Math.floor((totalW - 20) / 3), 80);
      const cellH  = Math.floor(Math.max(cellW * 0.8, 120));
      setMiniW(cellW);
      setMiniH(cellH);
    });
    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  // ── Draw loop ─────────────────────────────────────────────────────────────
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas || mapStatus !== 'ready' || !mapData) return;
    const ctx = canvas.getContext('2d')!;

    // Background
    ctx.fillStyle = '#0d1117';
    ctx.fillRect(0, 0, canvasW, canvasH);

    // Subtle grid
    ctx.strokeStyle = '#1a2235';
    ctx.lineWidth = 1;
    const gridSteps = 8;
    for (let i = 0; i <= gridSteps; i++) {
      const t = i / gridSteps;
      const gx = CANVAS_PAD + t * (canvasW - 2 * CANVAS_PAD);
      const gy = CANVAS_PAD + t * (canvasH - 2 * CANVAS_PAD);
      ctx.beginPath(); ctx.moveTo(gx, CANVAS_PAD); ctx.lineTo(gx, canvasH - CANVAS_PAD); ctx.stroke();
      ctx.beginPath(); ctx.moveTo(CANVAS_PAD, gy); ctx.lineTo(canvasW - CANVAS_PAD, gy); ctx.stroke();
    }

    // Points
    for (let i = 0; i < mapData.points.length; i++) {
      const p = mapData.points[i];
      if (filterCat && p.category !== filterCat) continue;

      const { x: cx, y: cy } = toCanvas(p.x, p.y);
      const isHovered = hoveredIdx === i;
      const color = CATEGORY_COLORS[p.category] ?? '#6b7280';
      const r = isHovered ? 8 : 5;

      // Glow ring on hover
      if (isHovered) {
        ctx.beginPath();
        ctx.arc(cx, cy, r + 5, 0, Math.PI * 2);
        ctx.strokeStyle = color + '55';
        ctx.lineWidth = 3;
        ctx.stroke();
        ctx.beginPath();
        ctx.arc(cx, cy, r + 2, 0, Math.PI * 2);
        ctx.strokeStyle = color;
        ctx.lineWidth = 1.5;
        ctx.stroke();
      }

      ctx.beginPath();
      ctx.arc(cx, cy, r, 0, Math.PI * 2);
      ctx.fillStyle = isHovered ? '#ffffff' : color;
      ctx.fill();
    }

    // Active / interpolation marker (yellow target)
    if (activeNorm) {
      const { x: cx, y: cy } = toCanvas(activeNorm.x, activeNorm.y);
      const rings = [{ r: 14, a: 0.3 }, { r: 9, a: 0.6 }];
      for (const { r, a } of rings) {
        ctx.beginPath();
        ctx.arc(cx, cy, r, 0, Math.PI * 2);
        ctx.strokeStyle = `rgba(245, 158, 11, ${a})`;
        ctx.lineWidth = 2;
        ctx.stroke();
      }
      ctx.beginPath();
      ctx.arc(cx, cy, 4, 0, Math.PI * 2);
      ctx.fillStyle = '#f59e0b';
      ctx.fill();
    }

    // Crosshair for current patch
    if (crosshairNorm) {
      const { x: cx, y: cy } = toCanvas(crosshairNorm.x, crosshairNorm.y);

      ctx.save();
      ctx.strokeStyle = 'rgba(255, 255, 255, 0.45)';
      ctx.lineWidth = 1;
      ctx.setLineDash([4, 5]);
      ctx.beginPath();
      ctx.moveTo(cx, CANVAS_PAD);
      ctx.lineTo(cx, canvasH - CANVAS_PAD);
      ctx.stroke();
      ctx.beginPath();
      ctx.moveTo(CANVAS_PAD, cy);
      ctx.lineTo(canvasW - CANVAS_PAD, cy);
      ctx.stroke();
      ctx.setLineDash([]);

      // Circle marker
      ctx.beginPath();
      ctx.arc(cx, cy, 7, 0, Math.PI * 2);
      ctx.strokeStyle = 'rgba(255, 255, 255, 0.8)';
      ctx.lineWidth = 1.5;
      ctx.stroke();

      // Label
      ctx.fillStyle = 'rgba(255, 255, 255, 0.6)';
      ctx.font = '10px monospace';
      const labelX = cx + 10 > canvasW - 80 ? cx - 72 : cx + 10;
      ctx.fillText('▶ current', labelX, cy - 10);
      ctx.restore();
    }
  }, [mapData, mapStatus, canvasW, canvasH, hoveredIdx, activeNorm, crosshairNorm, filterCat, toCanvas]);

  // ── Mini-map draw helper ──────────────────────────────────────────────────
  const drawMiniMap = useCallback((
    canvas:   HTMLCanvasElement | null,
    xKey:     keyof MapPoint,
    yKey:     keyof MapPoint,
    hovIdx:   number | null,
    activeN:  { x: number; y: number } | null,
    crossN:   { x: number; y: number } | null,
    w: number, h: number,
  ) => {
    if (!canvas || !mapData) return;
    const ctx = canvas.getContext('2d')!;
    ctx.fillStyle = '#0d1117';
    ctx.fillRect(0, 0, w, h);

    const pad = 14;
    const toC = (nx: number, ny: number) => ({
      x: pad + nx * (w - 2 * pad),
      y: pad + ny * (h - 2 * pad),
    });

    // Subtle grid
    ctx.strokeStyle = '#1a2235';
    ctx.lineWidth = 1;
    for (let i = 0; i <= 4; i++) {
      const t = i / 4;
      const gx = pad + t * (w - 2 * pad);
      const gy = pad + t * (h - 2 * pad);
      ctx.beginPath(); ctx.moveTo(gx, pad); ctx.lineTo(gx, h - pad); ctx.stroke();
      ctx.beginPath(); ctx.moveTo(pad, gy); ctx.lineTo(w - pad, gy); ctx.stroke();
    }

    for (let i = 0; i < mapData.points.length; i++) {
      const p = mapData.points[i];
      if (filterCat && p.category !== filterCat) continue;
      const nx = p[xKey] as number | undefined;
      const ny = p[yKey] as number | undefined;
      if (nx == null || ny == null) continue;
      const { x: cx, y: cy } = toC(nx, ny);
      const color = CATEGORY_COLORS[p.category] ?? '#6b7280';
      const isH   = hovIdx === i;
      const r     = isH ? 6 : 4;
      if (isH) {
        ctx.beginPath(); ctx.arc(cx, cy, r + 4, 0, Math.PI * 2);
        ctx.strokeStyle = color + '66'; ctx.lineWidth = 2; ctx.stroke();
      }
      ctx.beginPath(); ctx.arc(cx, cy, r, 0, Math.PI * 2);
      ctx.fillStyle = isH ? '#ffffff' : color;
      ctx.fill();
    }

    // Active marker
    if (activeN) {
      const { x: cx, y: cy } = toC(activeN.x, activeN.y);
      ctx.beginPath(); ctx.arc(cx, cy, 10, 0, Math.PI * 2);
      ctx.strokeStyle = 'rgba(245,158,11,0.35)'; ctx.lineWidth = 2; ctx.stroke();
      ctx.beginPath(); ctx.arc(cx, cy, 3, 0, Math.PI * 2);
      ctx.fillStyle = '#f59e0b'; ctx.fill();
    }

    // Crosshair
    if (crossN) {
      const { x: cx, y: cy } = toC(crossN.x, crossN.y);
      ctx.save();
      ctx.strokeStyle = 'rgba(255,255,255,0.4)'; ctx.lineWidth = 1;
      ctx.setLineDash([3, 4]);
      ctx.beginPath(); ctx.moveTo(cx, pad); ctx.lineTo(cx, h - pad); ctx.stroke();
      ctx.beginPath(); ctx.moveTo(pad, cy); ctx.lineTo(w - pad, cy); ctx.stroke();
      ctx.setLineDash([]);
      ctx.beginPath(); ctx.arc(cx, cy, 5, 0, Math.PI * 2);
      ctx.strokeStyle = 'rgba(255,255,255,0.7)'; ctx.lineWidth = 1.2; ctx.stroke();
      ctx.restore();
    }
  }, [mapData, filterCat]);

  // Crosshair positions for structured maps
  const { crossTimbre, crossDyn, crossMod } = useMemo(() => {
    if (!currentPatch || !mapData?.structured || !mapData.points.length) {
      return { crossTimbre: null, crossDyn: null, crossMod: null };
    }
    const src = patchToParamVector(currentPatch);
    let bestIdx = 0; let bestDist = Infinity;
    for (let i = 0; i < mapData.points.length; i++) {
      const p = mapData.points[i];
      if (!p.params.length) continue;
      let sq = 0;
      const len = Math.min(src.length, p.params.length, PARAM_DIM);
      for (let d = 0; d < len; d++) sq += (src[d] - p.params[d]) ** 2;
      if (sq < bestDist) { bestDist = sq; bestIdx = i; }
    }
    const np = mapData.points[bestIdx];
    return {
      crossTimbre: (np.x_timbre  != null && np.y_timbre  != null) ? { x: np.x_timbre,    y: np.y_timbre    } : null,
      crossDyn:    (np.x_dynamics != null && np.y_dynamics   != null) ? { x: np.x_dynamics,  y: np.y_dynamics  } : null,
      crossMod:    (np.x_modulation  != null && np.y_modulation  != null) ? { x: np.x_modulation, y: np.y_modulation } : null,
    };
  }, [currentPatch, mapData]);

  // Draw effects for the 3 mini-maps
  useEffect(() => {
    drawMiniMap(timbreCanvasRef.current, 'x_timbre', 'y_timbre', hoverTimbre, activeTimbre, crossTimbre, miniW, miniH);
  }, [drawMiniMap, hoverTimbre, activeTimbre, crossTimbre, miniW, miniH]);

  useEffect(() => {
    drawMiniMap(dynCanvasRef.current, 'x_dynamics', 'y_dynamics', hoverDyn, activeDyn, crossDyn, miniW, miniH);
  }, [drawMiniMap, hoverDyn, activeDyn, crossDyn, miniW, miniH]);

  useEffect(() => {
    drawMiniMap(modCanvasRef.current, 'x_modulation', 'y_modulation', hoverMod, activeMod, crossMod, miniW, miniH);
  }, [drawMiniMap, hoverMod, activeMod, crossMod, miniW, miniH]);

  // ── Hit-test: find nearest point within HIT_PX pixels ────────────────────
  const hitTest = useCallback((cx: number, cy: number): number | null => {
    if (!mapData) return null;
    let bestIdx = -1;
    let bestDist = HIT_PX;
    for (let i = 0; i < mapData.points.length; i++) {
      const p = mapData.points[i];
      if (filterCat && p.category !== filterCat) continue;
      const { x, y } = toCanvas(p.x, p.y);
      const d = Math.hypot(x - cx, y - cy);
      if (d < bestDist) { bestDist = d; bestIdx = i; }
    }
    return bestIdx >= 0 ? bestIdx : null;
  }, [mapData, filterCat, toCanvas]);

  // Hit-test helper for mini-maps using a head's coord key
  const hitTestHead = useCallback((
    cx: number, cy: number,
    xKey: keyof MapPoint, yKey: keyof MapPoint,
    w: number, h: number,
  ): number | null => {
    if (!mapData) return null;
    const pad = 14;
    const toC = (nx: number, ny: number) => ({
      x: pad + nx * (w - 2 * pad),
      y: pad + ny * (h - 2 * pad),
    });
    let bestIdx = -1; let bestDist = HIT_PX;
    for (let i = 0; i < mapData.points.length; i++) {
      const p = mapData.points[i];
      if (filterCat && p.category !== filterCat) continue;
      const nx = p[xKey] as number | undefined;
      const ny = p[yKey] as number | undefined;
      if (nx == null || ny == null) continue;
      const { x, y } = toC(nx, ny);
      const d = Math.hypot(x - cx, y - cy);
      if (d < bestDist) { bestDist = d; bestIdx = i; }
    }
    return bestIdx >= 0 ? bestIdx : null;
  }, [mapData, filterCat]);

  // ── KNN + IDW interpolation in z/param space ──────────────────────────────
  const knnInterpolate = useCallback((nx: number, ny: number): Float32Array | null => {
    if (!mapData || mapData.points.length < 2) return null;

    const active = mapData.points.filter(p => !filterCat || p.category === filterCat);
    if (active.length === 0) return null;

    // Find k nearest by Euclidean 2D distance
    const ranked = active
      .map((p, idx) => ({ idx, dist: Math.hypot(p.x - nx, p.y - ny) }))
      .sort((a, b) => a.dist - b.dist)
      .slice(0, KNN_K);

    // IDW weights: w_i = 1 / max(dist_i², ε)
    const weights = ranked.map(({ dist }) => 1 / Math.max(dist * dist, 1e-8));
    const wTotal  = weights.reduce((s, w) => s + w, 0);

    // Interpolate in latent (z) space when available, else param space
    const useZ  = mapData.has_z_vectors && modelReady;
    const vecKey: keyof MapPoint = useZ ? 'z_vector' : 'params';
    const dim   = useZ ? mapData.latent_dim : PARAM_DIM;

    const out = new Float32Array(dim);
    for (let k = 0; k < ranked.length; k++) {
      const w   = weights[k] / wTotal;
      const vec = active[ranked[k].idx][vecKey] as number[];
      for (let d = 0; d < dim; d++) out[d] += w * (vec[d] ?? 0);
    }
    return out;
  }, [mapData, filterCat, modelReady]);

  // ── Structured head IDW: interpolate a z slice, borrow other slices from nearest ──
  const knnInterpolateHead = useCallback((
    nx: number, ny: number,
    xKey: keyof MapPoint, yKey: keyof MapPoint,
    sliceStart: number, sliceEnd: number,
  ): { zSlice: Float32Array; nearestPoint: MapPoint } | null => {
    if (!mapData || !mapData.has_z_vectors || mapData.points.length < 2) return null;
    const active = mapData.points.filter(p =>
      (!filterCat || p.category === filterCat) &&
      p[xKey] != null && p[yKey] != null &&
      p.z_vector.length >= sliceEnd,
    );
    if (active.length === 0) return null;

    const ranked = active
      .map(p => ({ p, dist: Math.hypot((p[xKey] as number) - nx, (p[yKey] as number) - ny) }))
      .sort((a, b) => a.dist - b.dist)
      .slice(0, KNN_K);

    const weights = ranked.map(({ dist }) => 1 / Math.max(dist * dist, 1e-8));
    const wTotal  = weights.reduce((s, w) => s + w, 0);

    const dim = sliceEnd - sliceStart;
    const zSlice = new Float32Array(dim);
    for (let k = 0; k < ranked.length; k++) {
      const w = weights[k] / wTotal;
      for (let d = 0; d < dim; d++) zSlice[d] += w * ranked[k].p.z_vector[sliceStart + d];
    }
    return { zSlice, nearestPoint: ranked[0].p };
  }, [mapData, filterCat]);

  // ── Build and send a Patch from a param or z vector ───────────────────────
  const vectorToPatch = useCallback((
    vec: Float32Array,
    isZ: boolean,
    name: string,
  ): Patch | null => {
    if (!currentPatch) return null;
    if (isZ) {
      return variator.decodeLatent(vec, currentPatch);
    }
    return paramVectorToPatch(enforceValidity(vec), currentPatch, name);
  }, [currentPatch]);

  const sendToPreenFM = useCallback(async (patch: Patch) => {
    if (!midiOutput) return;
    setSending(true);
    clearNRPNQueue();
    for (const msg of patchToNRPNMessages(patch)) sendNRPN(msg, midiChannel);
    await drainNRPNQueue();
    setSending(false);
  }, [midiOutput, midiChannel]);

  // ── Structured head click/hover handlers ─────────────────────────────────
  const getMinimapCoords = (e: React.MouseEvent<HTMLCanvasElement>, w: number, h: number) => {
    const rect = (e.currentTarget as HTMLCanvasElement).getBoundingClientRect();
    const scaleX = w / rect.width;
    const scaleY = h / rect.height;
    return {
      cx: (e.clientX - rect.left) * scaleX,
      cy: (e.clientY - rect.top)  * scaleY,
    };
  };

  const normFromMini = (cx: number, cy: number, w: number, h: number) => {
    const pad = 14;
    return {
      x: (cx - pad) / Math.max(w - 2 * pad, 1),
      y: (cy - pad) / Math.max(h - 2 * pad, 1),
    };
  };

  const handleMiniClick = useCallback(async (
    e: React.MouseEvent<HTMLCanvasElement>,
    xKey: keyof MapPoint, yKey: keyof MapPoint,
    headType: 'osc' | 'env' | 'mat',
    setActive: (v: {x:number;y:number}) => void,
  ) => {
    if (!mapData || !currentPatch || sending || !modelReady) return;
    const { cx, cy } = getMinimapCoords(e, miniW, miniH);
    const { x: nx, y: ny } = normFromMini(cx, cy, miniW, miniH);
    setActive({ x: nx, y: ny });

    const oscEnd = Z_OSC_DIM;
    const envEnd = Z_OSC_DIM + Z_ENV_DIM;
    const matEnd = Z_OSC_DIM + Z_ENV_DIM + Z_MATRIX_DIM;

    // Interpolate the head's own z-slice; borrow others from nearest
    const result = knnInterpolateHead(
      nx, ny, xKey, yKey,
      headType === 'osc' ? 0      : headType === 'env' ? oscEnd : envEnd,
      headType === 'osc' ? oscEnd : headType === 'env' ? envEnd : matEnd,
    );
    if (!result) return;

    const { zSlice, nearestPoint: np } = result;
    const zOsc   = headType === 'osc' ? zSlice : new Float32Array(np.z_vector.slice(0,      oscEnd));
    const zEnv   = headType === 'env' ? zSlice : new Float32Array(np.z_vector.slice(oscEnd, envEnd));
    const zMat   = headType === 'mat' ? zSlice : new Float32Array(np.z_vector.slice(envEnd, matEnd));

    const patch = variator.decodeStructured(zOsc, zEnv, zMat, currentPatch);
    if (patch) await sendToPreenFM(patch);
  }, [mapData, currentPatch, sending, modelReady, miniW, miniH, knnInterpolateHead, sendToPreenFM]);

  // ── Mouse events ──────────────────────────────────────────────────────────
  const getCanvasCoords = (e: React.MouseEvent<HTMLCanvasElement>) => {
    const rect = canvasRef.current!.getBoundingClientRect();
    // Scale mouse coords from CSS pixels to canvas buffer pixels
    const scaleX = canvasW / rect.width;
    const scaleY = canvasH / rect.height;
    return {
      cx: (e.clientX - rect.left) * scaleX,
      cy: (e.clientY - rect.top)  * scaleY,
    };
  };

  const handleMouseMove = useCallback((e: React.MouseEvent<HTMLCanvasElement>) => {
    const { cx, cy } = getCanvasCoords(e);
    const idx = hitTest(cx, cy);
    setHoveredIdx(idx);

    if (idx !== null && mapData) {
      const p = mapData.points[idx];
      const { x: px, y: py } = toCanvas(p.x, p.y);
      // Position tooltip; keep it from going off the right edge
      const rect = canvasRef.current!.getBoundingClientRect();
      const cssScale = rect.width / canvasW;
      const tooltipX = px * cssScale + 12;
      const tooltipY = py * cssScale - 24;
      setTooltipStyle({ left: tooltipX, top: tooltipY });
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [hitTest, mapData, toCanvas, canvasW]);

  const handleClick = useCallback(async (e: React.MouseEvent<HTMLCanvasElement>) => {
    if (!mapData || !currentPatch || sending) return;
    const { cx, cy } = getCanvasCoords(e);
    const { x: nx, y: ny } = fromCanvas(cx, cy);
    setActiveNorm({ x: nx, y: ny });

    const hitIdx = hitTest(cx, cy);

    let patch: Patch | null = null;

    if (hitIdx !== null) {
      // ── Direct click on a point ─────────────────────────────────────────
      const p = mapData.points[hitIdx];
      const useZ = mapData.has_z_vectors && modelReady && p.z_vector.length === mapData.latent_dim;
      if (useZ) {
        patch = vectorToPatch(new Float32Array(p.z_vector), true, p.name);
      } else if (p.params.length >= PARAM_DIM) {
        patch = vectorToPatch(new Float32Array(p.params.slice(0, PARAM_DIM)), false, p.name);
      }
    } else {
      // ── Interpolation click ──────────────────────────────────────────────
      const interpVec = knnInterpolate(nx, ny);
      if (interpVec) {
        const isZ = mapData.has_z_vectors && modelReady && interpVec.length === mapData.latent_dim;
        patch = vectorToPatch(interpVec, isZ, 'interpolated');
      }
    }

    if (patch) await sendToPreenFM(patch);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [mapData, currentPatch, sending, hitTest, knnInterpolate, fromCanvas, vectorToPatch, sendToPreenFM, modelReady]);

  // ── Render ────────────────────────────────────────────────────────────────

  const pointCount = mapData?.points.length ?? 0;
  const canSend    = !!midiOutput;
  const allCats    = Object.keys(CATEGORY_COLORS);

  return (
    <Container>
      <Header>
        <Title>Latent Space Map</Title>
        <StatusRow>
          {mapStatus === 'ready' && <StatusTag>{pointCount} patches</StatusTag>}
          {mapData && <StatusTag>{mapData.method.toUpperCase()}</StatusTag>}
          <StatusTag title={modelReady ? 'Using trained CVAE decoder' : 'Neural decoder unavailable — using param-space interpolation'}>
            {modelReady ? '⚡ neural decoder' : '~ params mode'}
          </StatusTag>
          <StatusTag>{canSend ? '● MIDI ready' : '○ no MIDI'}</StatusTag>
        </StatusRow>
      </Header>

      {/* ── Category filter ──────────────────────────────────────────────── */}
      {mapStatus === 'ready' && (
        <FilterRow>
          <FilterLabel>Filtre :</FilterLabel>
          <FilterBtn $active={!filterCat} onClick={() => setFilterCat(null)}>
            Tous
          </FilterBtn>
          {allCats.map(cat => (
            <FilterBtn
              key={cat}
              $active={filterCat === cat}
              $color={CATEGORY_COLORS[cat]}
              onClick={() => setFilterCat(prev => prev === cat ? null : cat)}
            >
              {cat}
            </FilterBtn>
          ))}
        </FilterRow>
      )}

      {/* ── Canvas ───────────────────────────────────────────────────────── */}
      <CanvasWrap ref={wrapRef}>
        {mapStatus === 'loading' && (
          <Overlay>Chargement de la carte latente…</Overlay>
        )}
        {mapStatus === 'error' && (
          <Overlay>
            <span>Carte non disponible.</span>
            <span>Génère-la depuis la racine du projet :</span>
            <code>python scripts/generate_map.py</code>
            <span style={{ fontSize: '0.65rem', marginTop: 4 }}>
              puis relance le serveur de développement.
            </span>
          </Overlay>
        )}
        <StyledCanvas
          ref={canvasRef}
          width={canvasW}
          height={canvasH}
          style={{ cursor: sending ? 'wait' : hoveredIdx !== null ? 'pointer' : 'crosshair' }}
          onMouseMove={handleMouseMove}
          onMouseLeave={() => setHoveredIdx(null)}
          onClick={handleClick}
        />

        {/* Tooltip */}
        {hoveredIdx !== null && mapData && (() => {
          const p = mapData.points[hoveredIdx];
          return (
            <Tooltip style={tooltipStyle}>
              <TooltipName>{p.name}</TooltipName>
              <TooltipCat $color={CATEGORY_COLORS[p.category] ?? '#888'}>
                {p.category}
              </TooltipCat>
            </Tooltip>
          );
        })()}
      </CanvasWrap>

      {/* ── Legend ───────────────────────────────────────────────────────── */}
      <Legend>
        {allCats.map(cat => (
          <LegendItem key={cat}>
            <LegendDot $color={CATEGORY_COLORS[cat]} />
            <span>{cat}</span>
          </LegendItem>
        ))}
        <LegendItem>
          <LegendCrosshair />
          <span>position actuelle</span>
        </LegendItem>
      </Legend>

      {/* ── Structured 3-head mini-maps ───────────────────────────────────── */}
      {mapData?.structured && (
        <StructuredSection>
          <StructuredTitle>Structured Latent Space</StructuredTitle>
          <MapsGrid ref={mapsGridRef}>
            {/* Timbre */}
            <MiniMapWrap>
              <MiniMapLabel>🔊 Timbre</MiniMapLabel>
              <MiniCanvas
                ref={timbreCanvasRef}
                width={miniW} height={miniH}
                style={{ cursor: hoverTimbre !== null ? 'pointer' : 'crosshair' }}
                onMouseMove={e => {
                  const { cx, cy } = getMinimapCoords(e, miniW, miniH);
                  setHoverTimbre(hitTestHead(cx, cy, 'x_timbre', 'y_timbre', miniW, miniH));
                }}
                onMouseLeave={() => setHoverTimbre(null)}
                onClick={e => handleMiniClick(e, 'x_timbre', 'y_timbre', 'osc', setActiveTimbre)}
              />
            </MiniMapWrap>

            {/* Dynamics */}
            <MiniMapWrap>
              <MiniMapLabel>🥁 Dynamics</MiniMapLabel>
              <MiniCanvas
                ref={dynCanvasRef}
                width={miniW} height={miniH}
                style={{ cursor: hoverDyn !== null ? 'pointer' : 'crosshair' }}
                onMouseMove={e => {
                  const { cx, cy } = getMinimapCoords(e, miniW, miniH);
                  setHoverDyn(hitTestHead(cx, cy, 'x_dynamics', 'y_dynamics', miniW, miniH));
                }}
                onMouseLeave={() => setHoverDyn(null)}
                onClick={e => handleMiniClick(e, 'x_dynamics', 'y_dynamics', 'env', setActiveDyn)}
              />
            </MiniMapWrap>

            {/* Modulation */}
            <MiniMapWrap>
              <MiniMapLabel>🕸 Modulation</MiniMapLabel>
              <MiniCanvas
                ref={modCanvasRef}
                width={miniW} height={miniH}
                style={{ cursor: hoverMod !== null ? 'pointer' : 'crosshair' }}
                onMouseMove={e => {
                  const { cx, cy } = getMinimapCoords(e, miniW, miniH);
                  setHoverMod(hitTestHead(cx, cy, 'x_modulation', 'y_modulation', miniW, miniH));
                }}
                onMouseLeave={() => setHoverMod(null)}
                onClick={e => handleMiniClick(e, 'x_modulation', 'y_modulation', 'mat', setActiveMod)}
              />
            </MiniMapWrap>
          </MapsGrid>
          <HintRow style={{ marginTop: 6 }}>
            {modelReady
              ? 'Cliquer dans une mini-carte pour interpoler un seul axe musical'
              : '⚠ Chargement du décodeur CVAE en cours…'}
          </HintRow>
        </StructuredSection>
      )}

      {/* ── Hint ─────────────────────────────────────────────────────────── */}
      <HintRow>
        {sending
          ? '⏳ Envoi vers PreenFM3…'
          : !canSend
          ? 'Connecte une sortie MIDI pour activer l\'envoi.'
          : 'Cliquer sur un point pour l\'écouter · Cliquer entre les points pour interpoler'}
      </HintRow>
    </Container>
  );
}
